### ISSUE TITLE
Use OpenData terms data for class schedules

### ISSUE THREAD

**Issue by jswu** [UWFlow/rmc#115]
Right now we parse the [user's class schedule](https://gist.github.com/mduan/9334117) to get date and time information for their courses. This is undesirable because:

1. The class schedule format can vary across students, and is even ambiguous in some cases (#107)
2. Too much regex :(

Instead, we should simply parse out the current school term, along with the class number and section number of each course, and look it up in `SectionMeeting` (which is backed by [OpenData terms data](https://github.com/uWaterloo/api-documentation/blob/master/v2/terms/term_subject_schedule.md))

data/processor.py shows how the section data is processed (fetched by data/crawler.py)
server/static/js/schedule.js is where the schedule gets parsed.

**Comment by JGulbronson** [comment]
I believe this is done, we use OpenData for everything
