### ISSUE TITLE
Add a section on the profile page for scholarships

### ISSUE THREAD

**Issue by JGulbronson** [UWFlow/rmc#219]
In the near future, scholarship data for UW may be available through an API. It'd be great to automatically find scholarships the user is eligible for, and display them on the profile page. This will obviously have a UI element, so mockups would be a good place to start. In terms of filtering scholarships, @divad12 and I decided that filtering by program would constitute an MVP. Later, additional criteria such as grades or academic year could be added.

**Comment by divad12** [comment]
Any updates on this? I've some time during the break to review. At least, reply sooner than a few weeks! :P

Happy New Year!

**Comment by divad12** [comment]
np! Have fun in SF. Will see you there.

**Comment by JGulbronson** [comment]
So unfortunately I didn't get a chance this weekend, but I'll try to do a bit during the week. It really depends where the API is at from @KartikTalwar's side. The problem is, if fields are missing, it's tough to build the UI. (I could add my own, but I want to use realistic values). I'll try to push my branch tomorrow, so you can clone and take a look. 

Let me know when you're in SF @divad12!

**Comment by JGulbronson** [comment]
Update: Am actively working on it this week, and will try to do a bit each day. Am considering using fuzzy matching to determine which scholarships are available for students. @divad12 any thoughts on this approach? I'm hoping it'll help with cases where the program names don't completely match up.

**Comment by divad12** [comment]
Sorry, why do you need to use fuzzy matching? (For matching up faculty names?) Give me an example?

If you do need to do fuzzy matching, there's Python libraries for similar string matching (like Levenshtein distance).
