### ISSUE TITLE
BET100 is not showing up on Flow

### ISSUE THREAD

**Issue by aaronwinter** [UWFlow/rmc#221]
BET100 is not showing up in the results but others BET courses are.

**Comment by JGulbronson** [comment]
We get our course data from the OpenData API, so I suspect it's not being returned from there. Either way, there's a bug somewhere, so I can look in to it. Thanks for the heads up!

**Comment by Laxenade** [comment]
Hi, can you please retrieve the data again. BET 100 can be retrieved now

**Comment by JGulbronson** [comment]
Fixed
