### ISSUE TITLE
URL broken after parsing transcript

### ISSUE THREAD

**Issue by jasminer** [UWFlow/rmc#248]
After parsing s user's transcript, the user is automatically directed to a page, but the page is broken.

**Comment by JGulbronson** [comment]
Hey @jasminer thanks for filing the issue!

Could you provide a little more info on what happened? And perhaps what browser you're using? I was able to parse my transcript yesterday without issues, on the latest Chrome on OSX. 

Any extra info would be great!

**Comment by jasminer** [comment]
Ah I should've saved a screenshot...
I am on Windows 8.1, Chrome Version 46.0.2490.86 m. Would it be possible to delete my transcript from the system and try again?
Also, on a side note, enabling users to delete their course history would be a nice feature to have.

**Comment by JGulbronson** [comment]
Hmm, you can definitely open an issue about deleting course history.

It's odd that the redirect caused issues... did the transcript parse correctly?

**Comment by jasminer** [comment]
The transcript was parsed correctly, but I did not know until I clicked "back" in my browser and went to check my profile.

**Comment by JGulbronson** [comment]
That's odd.. you can always try parsing it locally, and see if you get the same error.

**Comment by jasminer** [comment]
Tried to parse again, it works now. I'll just assume it was a random error :)

**Comment by JGulbronson** [comment]
Thanks for opening the issue! If it happens again, we can always re-open it.
