### ISSUE TITLE
setup.sh requires sudo

### ISSUE THREAD

**Issue by MichalKononenko** [UWFlow/rmc#269]
I'm working on Flow from a Windows 10 laptop on Cygwin, and the setup.sh script is invoking sudo in a lot of places. I don't have sudo running on my machine, and I don't think Cygwin offers a sudo-like package.

Barring this, this looks like a security concern as the user running flow in production would be a sudoer. This opens up a vector for code injection attacks. In the same vein, isn't it best practice to not use sudo in the shell script and simply require that the user runs it as root? It seems like the better practice.

**Comment by divad12** [comment]
Good point! Want to submit a pull request?

**Comment by MichalKononenko** [comment]
I'll clean it up and send it in
