### ISSUE TITLE
Nav bar search seems to be broken

### ISSUE THREAD

**Issue by divad12** [UWFlow/rmc#270]
![image](https://cloud.githubusercontent.com/assets/159687/12694093/02345914-c6d6-11e5-96ce-46cb070a3966.png)

**Comment by AllenHW** [comment]
This seems to happen only when you are not logged in.

**Comment by AllenHW** [comment]
Will begin working once I get my environment set up (just cloned the repo today and having issues with starting the server) and get the course data

**Comment by JGulbronson** [comment]
Going to close for now as I can't reproduce. Tested by using Incognito mode on Chrome OSX, and search bar data loaded (eventually).
