### ISSUE TITLE
Dependencies are old

### ISSUE THREAD

**Issue by JGulbronson** [UWFlow/rmc#277]
Title says it all. Almost all of our dependencies, with the possible exception of Redis, are old. They haven't been updated in a while, making it difficult for people to get up and running locally. Should look in to seeing how everything can be made more "modern", and make it easier for people to set up. (Container perhaps?)

**Comment by JGulbronson** [comment]
Interestingly enough, there is already a Vagrant file

**Comment by divad12** [comment]
I think someone tried to get that set up, not sure if it ever worked though.
