### ISSUE TITLE
Unified search bar + course details not working + can't import schedule from quest

### ISSUE THREAD

**Issue by abhimohit99** [UWFlow/rmc#291]
The unified search bar doesn't work. When I search anything on it, the page simply reloads and doesn't do anything else.

Also, when I click on a course to see its details (ex. this page: https://uwflow.com/course/ece150), the page seems to load only the headers and footers and doesn't upload the main content. This picture below is what I see. 
![image](https://cloud.githubusercontent.com/assets/20718476/17239415/7f4233b0-5581-11e6-92b3-ac55df776847.png)
Funnily enough this issue only happens when I'm logged in. I can see the page properly if I view it while logged out.

Lastly, when I try to import my schedule from Quest into UWFlow, when I paste the details into the textbox, the textbox becomes 'uneditable' and nothing happens.

**Comment by JGulbronson** [comment]
Hmm, sorry to hear that! Would you be able to check if there's any output in the Chrome Developer Tools? Wondering if it's server side or client side.

**Comment by abhimohit99** [comment]
Okay as soon as I checked the website again everything's working fine. The search bar even gave suggestions this time! I can see all the pages properly now, and my schedule imported just fine! I have no idea what happened, but something you guys did fixed all of these problems perfectly. Thanks for the response though! Looking forward to using UW Flow more in the future :) :+1:
