### ISSUE TITLE
Please remove my name and student comment from UWFlow

### ISSUE THREAD

**Issue by mholland2304** [UWFlow/rmc#316]
Hello @JGulbronson and UWFlow Team. 

I kindly ask that you remove my name: Michael Holland from UW Flow and the comment(s) that a really difficult and angry student left on my name page. I taught Sociology (SOC) 322. 

I am still a student and it was my first course. I am not even a professor, so I don't see the point in having a student harm my image as a graduate student. 

I very, very, kindly request that you remove my information from your UWFlow Site. Please let me know:

michaelkholland@gmail.com

Thanks,

Michael Holland

**Comment by JGulbronson** [comment]
Hi Mike, they have been removed. In general I prefer to leave reviews up if I feel that they can help students make informed choices during course selection. However, as you are no longer teaching, this does not apply.

Regardless of how difficult of angry a student may have been, the review itself did not seem abusive or derogatory towards you, so had you still been teaching I would have likely leaned towards leaving it up.
