### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by csgregorian** [UWFlow/rmc#325]
![image](https://user-images.githubusercontent.com/3802671/43426479-9ea5d652-940a-11e8-81b6-7e72f10672f1.png)
Looks like the certificate expired this afternoon, got a Chrome security error when visiting the site.

**Comment by jlfwong** [comment]
Thanks for reporting this here! We'll look into it soon

**Comment by jlfwong** [comment]
@divad12 fixed it :) Thanks again for the report @csgregorian!
