### ISSUE TITLE
Information not updated for months on the site

### ISSUE THREAD

**Issue by yzgyyang** [UWFlow/rmc#328]
I noticed that the information is not updated on the site for months. Really hope that this could be fixed soon.

I'm definitely willing to help out if you need more hands ;-)

**Comment by jlfwong** [comment]
Hi @yzgyyang! We most definitely need people to take this on :) The project was started by a bunch of Software 2014 students, who have all graduated, then passed on to a Software 2017 student who has now also graduated! So we currently have no student maintainers, and frankly little motivation to contribute to a product we no longer use.

The [README.md](https://github.com/UWFlow/rmc/blob/master/README.md) should hopefully provide enough information to get started on development of UWFlow. Let me know if you run into problems.

**Comment by noryb009** [comment]
It looks like #329 didn't fix this as I hoped. Since updating works locally for me, are there any exceptions or other indications of what might be going wrong on?

**Comment by cchan** [comment]
@jlfwong you should admin @noryb009 !

**Comment by dshynkev** [comment]
This is now resolved.
