### ISSUE TITLE
Export to Google Calendar comes out blank

### ISSUE THREAD

**Issue by KMFSousa** [UWFlow/rmc#347]
Issue:
Looks like when I export my schedule the calendar is created but no events where in the calendar.

Prior State: 
I had a "uwflow.com schedule" calendar already from a previous term. After exporting the first time I deleted it and tried again and it was still blank.

Thoughts: 
Wondering if the events ended up in a wrong year, or if the .ics is just blank entirely.

**Comment by AyushK1** [comment]
Hi! Thanks for posting this issue. We're looking into it. I'll update this thread as we progress towards resolution.

**Comment by KMFSousa** [comment]
@AyushK1 Hey, looks like it did eventually update. There was some sort of delay in the service. If this is common we should probably give a pop up or notification as such.

Mitchell Strong also had an issue like this. He did not delete his older calendar and it never updated (going on 2 days since he tried to add it via the export a couple times)

**Comment by dshynkev** [comment]
It seems that Google Calendar caches calendars in some unspecified way, such that our caching policy has no effect on retention time on their side. Removing the subscription and adding it again will not help; the caching appears to be globally keyed on the URL. In fact, even different Google accounts will see the same unupdated calendar when using the same URL.

It is expected that eventually every calendar should update, but it is not clear how long this can take at most or what the best way to handle this on our side is. We are continuing our investigation.

**Comment by KMFSousa** [comment]
Sounds like that means it’s a limitation from a Google. If that’s a case we should file a bug against them. (Feedback through Calendar might work. Click (?) then click ‘Send Feedback’)

In the mean time a notice that a delay will likely occur would avoid that annoyance.

**Comment by jlfwong** [comment]
I wonder if it might work to be able to generate a new google calendar URL and invalidate the old URL path completely. Google calendar would then invalidate their cache. It might even work to tack on random URL parameters that do nothing.

**Comment by dshynkev** [comment]
@jlfwong this does work, yes, and some in fact [recommend it](https://helpme.teamsnap.com/article/315-team-schedule-is-not-updating-in-google-calendar). We're still trying to see if it's possible to avoid that.

This issue [has been reported](https://support.google.com/calendar/thread/954580?hl=en) to Google and a [similar one](https://answers.microsoft.com/en-us/outlook_com/forum/all/calendar-subscription-does-not-refresh/b289bba4-6fc2-4711-85a1-528de6b7ef81) was reported to Microsoft a long time ago. As far as I know, neither one has been or is being fixed.

**Comment by AyushK1** [comment]
@KMFSousa we have deployed a fix which generates a new calendar URL every export. This should resolve the issue. Let us know if it crops up again!
