### ISSUE TITLE
Cannot access uwflow.com

### ISSUE THREAD

**Issue by gzcharleszhang** [UWFlow/rmc#358]
I tried accessing `uwflow.com` on both my Mac (using home wifi) and iPhone (using cellular data), on both Chrome and Safari, I get the same error.
![Screen Shot 2020-10-13 at 4 18 50 PM](https://user-images.githubusercontent.com/26018804/95912053-47fa0d00-0d70-11eb-9764-f085c11d8f91.png)

I tried `ping uwflow.com` from my terminal, it seems to be fine.

**Comment by edwinzhng** [comment]
We just tested this with ~8 devices and only encountered a connection timeout once, seems like it's just a transient network issue with DigitalOcean or CloudFlare since the server is up and running without issue

**Comment by gzcharleszhang** [comment]
Weird, I've been encountering this same issue for the past 24 hours.

**Comment by edwinzhng** [comment]
Oh interesting thanks for letting us know, I just restarted the server so hopefully it'll resolve itself but ping me again if it's still down and I'll take a closer look tomorrow

**Comment by gzcharleszhang** [comment]
Hi @edwinzhng, I am still encountering that same issue on my device. I also tried accessing the site from a new device on a different network, and I got the same error.

**Comment by gzcharleszhang** [comment]
Just to add on, some of my friends are also running into the same issues while some are not.

**Comment by yayimahuman** [comment]
Hi @gzcharleszhang, we were unable to repro the issue using multiple devices + multiple users + multiple networks.

If you could find out a reliable repro between your devices (IPs, geographic location) and your friends devices, please let us know.

**Comment by edwinzhng** [comment]
@gzcharleszhang actually it seems like some other people have encountered this issue when using Cloudflare + DigitalOcean. It might be due to Cloudflare IPs that I need to whitelist on our server (https://community.cloudflare.com/t/community-tip-fixing-error-522-connection-timed-out/42325). I'll try that later and get back to you

**Comment by edwinzhng** [comment]
@gzcharleszhang can you check again to see if it works for you? We changed hosts and recreated our Cloudflare setup so that should resolve any issues

**Comment by gzcharleszhang** [comment]
@edwinzhng it works for me now, thanks for the help!
